<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYqzqKLh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYqzqKLh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYqzqKLh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYqzqKLh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYqzqKLh\App_KernelDevDebugContainer([
    'container.build_hash' => 'YqzqKLh',
    'container.build_id' => '333b2b9e',
    'container.build_time' => 1680696211,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYqzqKLh');
