<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4mJxc7s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4mJxc7s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4mJxc7s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4mJxc7s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4mJxc7s\App_KernelDevDebugContainer([
    'container.build_hash' => '4mJxc7s',
    'container.build_id' => '4e8e67f7',
    'container.build_time' => 1680994706,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4mJxc7s');
