<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErnJ7ZH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErnJ7ZH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerErnJ7ZH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerErnJ7ZH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerErnJ7ZH\App_KernelDevDebugContainer([
    'container.build_hash' => 'ErnJ7ZH',
    'container.build_id' => 'a64f1fcd',
    'container.build_time' => 1681000724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErnJ7ZH');
