<?php

namespace ContainerJxRw8HE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReadingTimeCalculatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ReadingTimeCalculator' shared autowired service.
     *
     * @return \App\Service\ReadingTimeCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service "App\\Service\\ReadingTimeCalculator": argument "$wordsPerMinute" of method "__construct()" is type-hinted "int", you should configure its value explicitly.');
    }
}
